apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf-new
data:
  nginx.conf: |
   server {
        listen       80;
        server_name  _;

        root /usr/share/nginx/html;
        index index.html index.htm;

        access_log /var/lib/logs/nginx-access.log main;
        error_log  /var/lib/logs/nginx-error.log error;



        location / {
           error_page   500 502 503 504  /50x.html;
           auth_basic "Restricted Content";
           auth_basic_user_file /etc/nginx/conf.d/.userpasswd;
           }

        location = /50x.html {
            root   /usr/share/nginx/html;
            }
        sub_filter_once off;
        sub_filter 'server_hostname' '$hostname';
        sub_filter 'server_address' '$server_addr:$server_port';
        sub_filter 'nginx_version' '$nginx_version';
     }
  .userpasswd: |
         admin:H2KuAlYtSLpKM
