apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: ngi
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ngi
  template:
    metadata:
      labels:
        name: ngi
    spec:
      hostname: nginxfordemo
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /etc/nginx/conf.d/ # mount nginx-conf volume to /etc/nginx
          readOnly: true
          name: nginx-conf
        - mountPath: /var/lib/logs
          name: nfs-vol
        - mountPath: /usr/share/nginx/html
          name: nfs-www
      volumes:
      - name: nfs-vol
        persistentVolumeClaim:
            claimName: nfs-log-pvc
      - name: nfs-www
        persistentVolumeClaim:
            claimName: nfs-html-pvc
      - name: nginx-conf
        configMap:
          name: nginx-conf-new # place ConfigMap `nginx-conf` on /etc/nginx
          items:
            - key: nginx.conf
              path: nginx.conf
            - key: .userpasswd
              path: .userpasswd
